default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  database: my_database_development

test:
  <<: *default
  database: my_database_test

  url: <%= ENV['DATABASE_URL'] %>
